### ISSUE TITLE
Update the user interface and install in FritzBox 6820 V1

### ISSUE THREAD

**Issue by rishihashbinary** [Freetz/freetz#268] opened 2020-02-27 11:03 UTC
Hi, I was trying to update the user interface by changing the CSS file (freetz/build/modified/filesystem/usr/www/avm/css/rd/main.css) also tried changing few images to check for the update, 
Post `make menuconfig` and `make` command, I was able to see an image file in my **images** directory
However, I tried to copy the image file using ADAM2 interface in mtd4, upon rebooting the router, no changes were been reflected in the user interface.
Can you help me with the correct process in case I am doing anything wrong here?

reference links
https://freetz.github.io/wiki/help/howtos/common/newbie
https://openwrt.org/toh/avm/fritz.box.wlan.3370#serial

**Comment by er13** [comment] 2020-03-08 22:33
Closing as duplicate of https://github.com/Freetz/freetz/issues/270.

**Closed by er13** 2020-03-08 22:33 UTC
